import Head from 'next/head';
import { FormEventHandler, useState } from 'react';
import axios from 'axios';
import { useSession, signIn, signOut } from 'next-auth/react';
import styled from 'styled-components';

export default function Home() {
	return <></>;
	// const [userData, setUserData] = useState({
	// 	email: '',
	// 	name: '',
	// 	password: '',
	// 	displayName: '',
	// 	role: 'ADMIN',
	// });
	// const { data: session, status, update } = useSession();
	// const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
	// 	e.preventDefault();

	// 	const returnedUser = await axios.post('/api/users', {
	// 		...userData,
	// 	});
	// };

	// // useEffect(() => {
	// // 	signIn();
	// // }, []);

	// if (session) {
	// 	return (
	// 		<>
	// 			<Paragraph>Paragraph Text</Paragraph>
	// 			<h2>Header Text</h2>
	// 			Signed in as {session.user.email} <br />
	// 			<button onClick={() => signOut()}>Sign out</button>
	// 		</>
	// 	);
	// }
	// return (
	// 	<>
	// 		Not signed in <br />
	// 		<button onClick={() => signIn()}>Sign in</button>
	// 	</>
	// );

	// return (
	// 	<>
	// 		<Head>
	// 			<title>Create Next App</title>
	// 			<meta name='description' content='Generated by create next app' />
	// 			<meta name='viewport' content='width=device-width, initial-scale=1' />
	// 			<link rel='icon' href='/favicon.ico' />
	// 		</Head>
	// 		<main>
	// 			<form
	// 				onSubmit={(e) => handleSubmit(e)}
	// 				style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}
	// 			>
	// 				<h2>SIGN UP</h2>
	// 				<label>
	// 					Email:
	// 					<input
	// 						onChange={(e) =>
	// 							setUserData((prevData) => ({
	// 								...prevData,
	// 								email: e.target.value,
	// 							}))
	// 						}
	// 						type='email'
	// 					/>
	// 				</label>
	// 				<label>
	// 					Name:
	// 					<input
	// 						onChange={(e) =>
	// 							setUserData((prevData) => ({
	// 								...prevData,
	// 								name: e.target.value,
	// 							}))
	// 						}
	// 						type='text'
	// 					/>
	// 				</label>
	// 				<label>
	// 					Display Name:
	// 					<input
	// 						onChange={(e) =>
	// 							setUserData((prevData) => ({
	// 								...prevData,
	// 								displayName: e.target.value,
	// 							}))
	// 						}
	// 						type='text'
	// 					/>
	// 				</label>
	// 				<label>
	// 					Password:
	// 					<input
	// 						onChange={(e) =>
	// 							setUserData((prevData) => ({
	// 								...prevData,
	// 								password: e.target.value,
	// 							}))
	// 						}
	// 						type='password'
	// 						autoComplete='current password'
	// 					/>
	// 				</label>
	// 				<button>SUBMIT</button>
	// 			</form>
	// 			<div>WELCOME {userData.displayName}</div>
	// 		</main>
	// 	</>
	// );
}

const Paragraph = styled.div`
	padding: 4rem;
	background-color: red;
`;
